"""Data models for preprocessor output."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass
class PreprocessedPaper:
    """Structured output from paper content preprocessing.

    The three ``*_split`` lists provide the same paper content at different
    granularity levels — useful for downstream classification and retrieval:

    * ``sections_split``   — one string per logical section.
    * ``paragraphs_split`` — one string per paragraph.
    * ``sentences_split``  — one string per sentence.

    ``table_descriptions`` are short natural-language summaries generated by
    an LLM (see :mod:`preprocessor.table_summarizer`).  They are empty when
    table summarisation is skipped.
    """

    # --- Section-level structured output ---
    sections: dict[str, list[str]] = field(default_factory=dict)

    # --- Three split levels for downstream tasks ---
    sections_split: list[str] = field(default_factory=list)
    paragraphs_split: list[str] = field(default_factory=list)
    sentences_split: list[str] = field(default_factory=list)

    # --- Extracted elements ---
    table_descriptions: list[str] = field(default_factory=list)
    math_map: dict[str, str] = field(default_factory=dict)
    links_map: dict[str, str] = field(default_factory=dict)

    success: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-friendly dictionary."""
        return asdict(self)


@dataclass
class PreprocessedMarkdown:
    """Structured output from markdown (model card / README) preprocessing.

    Uses the same three-level split scheme as :class:`PreprocessedPaper`.
    Additionally stores extracted code blocks, links, and emails.
    """

    # --- Three split levels ---
    sections_split: list[str] = field(default_factory=list)
    paragraphs_split: list[str] = field(default_factory=list)
    sentences_split: list[str] = field(default_factory=list)

    # --- Extracted elements ---
    codes: list[Any] = field(default_factory=list)
    tables: list[Any] = field(default_factory=list)
    links: list[str] = field(default_factory=list)
    emails: list[str] = field(default_factory=list)

    success: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-friendly dictionary."""
        return asdict(self)
